#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16g,walltime=18:00:00
#PBS -N roitracking
#PBS -V

set -e

echo "warping coordinates from mni space"
time singularity exec -e docker://brainlife/ants:2.2.0 ./CoordTransform.sh


